#pragma once

/**
 * @file version.hpp
 * @brief SyncFlow version information (auto-generated by CMake)
 */

#define SYNCFLOW_VERSION_MAJOR 0
#define SYNCFLOW_VERSION_MINOR 1
#define SYNCFLOW_VERSION_PATCH 0

#define SYNCFLOW_VERSION_STRING "0.1.0"
#define SYNCFLOW_VERSION_DESCRIPTION "Production-grade P2P file synchronization system"

/// Full version string for display
#define SYNCFLOW_FULL_VERSION "SyncFlow v" SYNCFLOW_VERSION_STRING " (SyncFlow)"

/// Git commit hash (if available during build)
#define SYNCFLOW_GIT_COMMIT ""

/// Build timestamp
#define SYNCFLOW_BUILD_TIMESTAMP ""

/// C++ Standard version used
#define SYNCFLOW_CXX_STANDARD 20

namespace syncflow {

/// Get version major number
inline constexpr int version_major() { return SYNCFLOW_VERSION_MAJOR; }

/// Get version minor number
inline constexpr int version_minor() { return SYNCFLOW_VERSION_MINOR; }

/// Get version patch number
inline constexpr int version_patch() { return SYNCFLOW_VERSION_PATCH; }

/// Get full version string
inline constexpr const char* version_string() { return SYNCFLOW_VERSION_STRING; }

}  // namespace syncflow
