if(EXISTS "/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_version_vector[1]_tests.cmake")
  include("/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_version_vector[1]_tests.cmake")
else()
  add_test(test_version_vector_NOT_BUILT test_version_vector_NOT_BUILT)
endif()
