if(EXISTS "/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_chunk_hasher[1]_tests.cmake")
  include("/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_chunk_hasher[1]_tests.cmake")
else()
  add_test(test_chunk_hasher_NOT_BUILT test_chunk_hasher_NOT_BUILT)
endif()
