if(EXISTS "/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_sync_diff[1]_tests.cmake")
  include("/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_sync_diff[1]_tests.cmake")
else()
  add_test(test_sync_diff_NOT_BUILT test_sync_diff_NOT_BUILT)
endif()
