if(EXISTS "/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_crypto[1]_tests.cmake")
  include("/mnt/myworld/dev/open_source_projects/syncflow/android/tests/test_crypto[1]_tests.cmake")
else()
  add_test(test_crypto_NOT_BUILT test_crypto_NOT_BUILT)
endif()
